### ISSUE TITLE
Error Icon

### ISSUE THREAD

**Issue by Tony931023** [FusionGen/FusionGEN#125]
loading an item in the armory releases this error
```
/home/cloud/amanthul-web/application/modules/icon/controllers/icon.php on line 145 .jpg' />
```

http://www.amanthul.nat.cu/item/2/1927

### Log Nginx
```
2022/04/01 14:25:22 [error] 162320#162320: *579 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_string() in /home/cloud/amanthul-web/application/modules/icon/controllers/icon.php:145
Stack trace:
#0 /home/cloud/amanthul-web/application/modules/icon/controllers/icon.php(129): Icon->xmlToArray('<?xml version="...')
#1 /home/cloud/amanthul-web/application/modules/icon/controllers/icon.php(82): Icon->getIconName('1927')
#2 /home/cloud/amanthul-web/application/modules/icon/controllers/icon.php(28): Icon->getDisplayName('19276')
#3 /home/cloud/amanthul-web/system/core/CodeIgniter.php(356): Icon->get('2', '1927')
#4 /home/cloud/amanthul-web/index.php(228): require_once('/home/cloud/ama...')
#5 {main}
  thrown in /home/cloud/amanthul-web/application/modules/icon/controllers/icon.php on line 145" while reading response header from upstream, client: 181.225.253.115, server: amanthul.nat.cu, request: "GET /icon/get/2/1927 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.1-fpm.sock:", host: "www.amanthul.nat.cu", referrer: "http://www.amanthul.nat.cu/item/2/1927"

```

**Comment by Err0r1** [comment]
Install simplexml PHP extension.

**Comment by Tony931023** [comment]
apt install php7.1-xml -y && systemctl restart nginx

> Install simplexml PHP extension.

Thanks
